<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="NUnit" Version="4.2.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>
</Project>
