// <auto-generated>
//     This code was generated by a tool. Changes will be overwritten.
// </auto-generated>
namespace Billing;

public partial class InvoiceProcessor
{
    public static int CompareByInvoiceId(InvoiceProcessor a, InvoiceProcessor b)
    {
        if (a.InvoiceId < b.InvoiceId)
            return -1;
        if (a.InvoiceId > b.InvoiceId)
            return 1;
        return 0;
    }
}
