//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing;

public partial class TaxTable
{
    public decimal RateFor(string region) => region == "US" ? 0.07m : 0.20m;
}
